### ISSUE TITLE
TypeError: MobileBrowser is not a function

### ISSUE THREAD

**Issue by freeneutron** [w3c/mobile-web-browser-emulator#10]
This example does not work!
TypeError: MobileBrowser is not a function

**Comment by tripu** [comment]
@freeneutron, can you paste the entire output, or give us more details about this error?

**Comment by freeneutron** [comment]
Sorry, I can not reproduce the bug again. Probably because of the lack silentserver.

**Comment by tripu** [comment]
Closing the issue then. @freeneutron, please reopen it, or ping us, if it reoccurs.
