### ISSUE TITLE
Fix .travis-setup.sh

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/mobile-web-browser-emulator#13]
Hey,

So after we discussed it with @tripu, it appeared that we need to fix the `.travis-setup.sh`. `sudo` is not possible anymore on travis. So it's getting harder to install chrome.

So we have 2 possibilities:
- Travis supports firefox. It's pre-installed on it. We switch to Firefox -> fixed
- We try to find a pre-compiled version of chrome, or create one, upload it somewhere and use it on travis

@dontcallmedom what do you think?

**Comment by dontcallmedom** [comment]
sorry, I won't have the cycles to look into this before end of next week; please do ping me again thoug

**Comment by tripu** [comment]
@guibbs, maybe fixing this issue will fix [builds of Mobile-Checker](https://github.com/w3c/Mobile-Checker/pull/123#issuecomment-161214525)! Those are broken, too :(
