### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by qwertychouskie** [w3c/mobile-web-browser-emulator#17]
Now that #15 is merged, can you update the NPM module?  I'm going to try to start working on https://github.com/w3c/Mobile-Checker/pull/140 again but need this module updated.

**Comment by tripu** [comment]
@qwertychouskie, I just did that ([`https://www.npmjs.com/package/mobile-web-browser-emulator`, version `0.0.6`](https://www.npmjs.com/package/mobile-web-browser-emulator)). I'm sorry for the long delay.

@dontcallmedom :arrow_up:

**Comment by qwertychouskie** [comment]
@tripu Thanks!  No problem.
