### ISSUE TITLE
chromedriver orphan processes

### ISSUE THREAD

**Issue by guibbs** [w3c/mobile-web-browser-emulator#7]
@dontcallmedom, apparently the Mobile Checker leaves some chromedriver orphans behind him. Seems like the browser.close() (and so as the driver.quit()) function doesn't work properly . It close google chrome, but not the chrome driver process.

I tried to find a solution, update dependencies but impossible to fix it right now.
Hope you have an idea.

**Comment by dontcallmedom** [comment]
how did you update the dependencies? I've pushed #8 that actually does it, since it required some changes to the code to be compatible with the latest version of selenium-webdriver.

Can you highlight a step by step process (or even better, a test case) under which there is always an orphan process remaining at the end of the execution? It would make it easier to identify the bug.

**Comment by guibbs** [comment]
Hi @dontcallmedom , 
I found why. The problems comes from [headless]() + mobile-web-browser-emulator.

this code close properly the chrome driver process:
```
var webdriver = require('selenium-webdriver');
var chrome = require('selenium-webdriver/chrome');
var chromedriver = require('chromedriver');
var headless = require('headless');
var events = require('events');

var capabilities = webdriver.Capabilities.chrome();
var options = new chrome.Options();
capabilities.merge(options.toCapabilities());
var service = new chrome.ServiceBuilder(chromedriver.path).build();
chrome.setDefaultService(service);
driver = new webdriver.Builder().
            withCapabilities(capabilities).
            build();
driver.get('http://google.com');
 driver.quit();
```

this code fails and keeps a chromedriver opened in the processes list until we close the node app:
```

    headless({
        display: {
            width: 320,
            height: 550
        }
    }, function(err, childProcess, servernum) {
        var capabilities = webdriver.Capabilities.chrome();
var options = new chrome.Options();
        //options.addArguments(["--enable-viewport-meta"]);
        options.addArguments(['--disable-bundled-ppapi-flash']);

        capabilities.merge(options.toCapabilities());



        var service = new chrome.ServiceBuilder(chromedriver.path).build();
        chrome.setDefaultService(service);
        
        driver = new webdriver.Builder().
            withCapabilities(capabilities).
            build();
        
        driver.get('http://google.com');

        driver.quit();
    })
```

**Comment by guibbs** [comment]
```
childProcess.kill()
```
Thanks @dontcallmedom
